  - name: Checkout
    uses: actions/checkout@v2
    with:
      fetch-depth: 0 # <-- clone with complete history
  - name: Push
    uses: heussd/mirror-to-bitbucket-github-action@v2
    with:
      username: lazorlux
      spacename: changemyavatarparams
      repository: cmap2-client
      password: ${{ secrets.BITBUCKET_PASSWORD }}
